apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: frontend
    spec:
      containers:
      - image: edaral3/ayd2grupo15_frontend:latest
        name: frontend
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
