apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ordenes
  name: ordenes
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: ordenes
    spec:
      containers:
      - image: edaral3/ayd2grupo15_productos:latest
        name: ordenes
        ports:
        - containerPort: 4007
        resources: {}
      restartPolicy: Always
status: {}
