apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: ordenes
  name: ordenes
spec:
  ports:
  - name: "4007"
    port: 4007
    targetPort: 4007
  selector:
    io.kompose.service: ordenes
status:
  loadBalancer: {}
