apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: productos
  name: productos
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: productos
    spec:
      containers:
      - image: edaral3/ayd2grupo15_productos:latest
        name: productos
        ports:
        - containerPort: 9001
        resources: {}
      restartPolicy: Always
status: {}
