apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-put
  name: user-put
spec:
  ports:
  - name: "4004"
    port: 4004
    targetPort: 4004
  selector:
    io.kompose.service: user-put
status:
  loadBalancer: {}
