apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-post
  name: user-post
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: user-post
    spec:
      containers:
      - image: edaral3/ayd2grupo15_user_post:latest
        name: user-post
        ports:
        - containerPort: 4001
        resources: {}
      restartPolicy: Always
status: {}
