apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-login
  name: user-login
spec:
  ports:
  - name: "4003"
    port: 4003
    targetPort: 4003
  selector:
    io.kompose.service: user-login
status:
  loadBalancer: {}
