apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: user-delete
  name: user-delete
spec:
  ports:
  - name: "4005"
    port: 4005
    targetPort: 4005
  selector:
    io.kompose.service: user-delete
status:
  loadBalancer: {}
